name: Auto Pull on Server

on:
  push:
    branches: [main]  # Change to your branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH and Pull
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd ${{ secrets.PROJECT_DIR }}
          git pull origin main  # Change to your branch